-- Table grants
GRANT DELETE ON public.admin_actions TO anon;
GRANT INSERT ON public.admin_actions TO anon;
GRANT SELECT ON public.admin_actions TO anon;
GRANT UPDATE ON public.admin_actions TO anon;
GRANT DELETE ON public.admin_actions TO authenticated;
GRANT INSERT ON public.admin_actions TO authenticated;
GRANT SELECT ON public.admin_actions TO authenticated;
GRANT UPDATE ON public.admin_actions TO authenticated;
GRANT DELETE ON public.admin_actions TO service_role;
GRANT INSERT ON public.admin_actions TO service_role;
GRANT SELECT ON public.admin_actions TO service_role;
GRANT UPDATE ON public.admin_actions TO service_role;
GRANT DELETE ON public.card_events TO anon;
GRANT INSERT ON public.card_events TO anon;
GRANT SELECT ON public.card_events TO anon;
GRANT UPDATE ON public.card_events TO anon;
GRANT DELETE ON public.card_events TO authenticated;
GRANT INSERT ON public.card_events TO authenticated;
GRANT SELECT ON public.card_events TO authenticated;
GRANT UPDATE ON public.card_events TO authenticated;
GRANT DELETE ON public.card_events TO service_role;
GRANT INSERT ON public.card_events TO service_role;
GRANT SELECT ON public.card_events TO service_role;
GRANT UPDATE ON public.card_events TO service_role;
GRANT DELETE ON public.leads TO anon;
GRANT INSERT ON public.leads TO anon;
GRANT SELECT ON public.leads TO anon;
GRANT UPDATE ON public.leads TO anon;
GRANT DELETE ON public.leads TO authenticated;
GRANT INSERT ON public.leads TO authenticated;
GRANT SELECT ON public.leads TO authenticated;
GRANT UPDATE ON public.leads TO authenticated;
GRANT DELETE ON public.leads TO service_role;
GRANT INSERT ON public.leads TO service_role;
GRANT SELECT ON public.leads TO service_role;
GRANT UPDATE ON public.leads TO service_role;
GRANT DELETE ON public.nfc_cards TO anon;
GRANT INSERT ON public.nfc_cards TO anon;
GRANT SELECT ON public.nfc_cards TO anon;
GRANT UPDATE ON public.nfc_cards TO anon;
GRANT DELETE ON public.nfc_cards TO authenticated;
GRANT INSERT ON public.nfc_cards TO authenticated;
GRANT SELECT ON public.nfc_cards TO authenticated;
GRANT UPDATE ON public.nfc_cards TO authenticated;
GRANT DELETE ON public.nfc_cards TO service_role;
GRANT INSERT ON public.nfc_cards TO service_role;
GRANT SELECT ON public.nfc_cards TO service_role;
GRANT UPDATE ON public.nfc_cards TO service_role;
GRANT DELETE ON public.profile_links TO anon;
GRANT INSERT ON public.profile_links TO anon;
GRANT SELECT ON public.profile_links TO anon;
GRANT UPDATE ON public.profile_links TO anon;
GRANT DELETE ON public.profile_links TO authenticated;
GRANT INSERT ON public.profile_links TO authenticated;
GRANT SELECT ON public.profile_links TO authenticated;
GRANT UPDATE ON public.profile_links TO authenticated;
GRANT DELETE ON public.profile_links TO service_role;
GRANT INSERT ON public.profile_links TO service_role;
GRANT SELECT ON public.profile_links TO service_role;
GRANT UPDATE ON public.profile_links TO service_role;
GRANT DELETE ON public.profile_media TO anon;
GRANT INSERT ON public.profile_media TO anon;
GRANT SELECT ON public.profile_media TO anon;
GRANT UPDATE ON public.profile_media TO anon;
GRANT DELETE ON public.profile_media TO authenticated;
GRANT INSERT ON public.profile_media TO authenticated;
GRANT SELECT ON public.profile_media TO authenticated;
GRANT UPDATE ON public.profile_media TO authenticated;
GRANT DELETE ON public.profile_media TO service_role;
GRANT INSERT ON public.profile_media TO service_role;
GRANT SELECT ON public.profile_media TO service_role;
GRANT UPDATE ON public.profile_media TO service_role;
GRANT DELETE ON public.profile_themes TO anon;
GRANT INSERT ON public.profile_themes TO anon;
GRANT SELECT ON public.profile_themes TO anon;
GRANT UPDATE ON public.profile_themes TO anon;
GRANT DELETE ON public.profile_themes TO authenticated;
GRANT INSERT ON public.profile_themes TO authenticated;
GRANT SELECT ON public.profile_themes TO authenticated;
GRANT UPDATE ON public.profile_themes TO authenticated;
GRANT DELETE ON public.profile_themes TO service_role;
GRANT INSERT ON public.profile_themes TO service_role;
GRANT SELECT ON public.profile_themes TO service_role;
GRANT UPDATE ON public.profile_themes TO service_role;
GRANT DELETE ON public.profiles TO anon;
GRANT INSERT ON public.profiles TO anon;
GRANT SELECT ON public.profiles TO anon;
GRANT UPDATE ON public.profiles TO anon;
GRANT DELETE ON public.profiles TO authenticated;
GRANT INSERT ON public.profiles TO authenticated;
GRANT SELECT ON public.profiles TO authenticated;
GRANT UPDATE ON public.profiles TO authenticated;
GRANT DELETE ON public.profiles TO service_role;
GRANT INSERT ON public.profiles TO service_role;
GRANT SELECT ON public.profiles TO service_role;
GRANT UPDATE ON public.profiles TO service_role;
GRANT DELETE ON public.rate_limits TO anon;
GRANT INSERT ON public.rate_limits TO anon;
GRANT SELECT ON public.rate_limits TO anon;
GRANT UPDATE ON public.rate_limits TO anon;
GRANT DELETE ON public.rate_limits TO authenticated;
GRANT INSERT ON public.rate_limits TO authenticated;
GRANT SELECT ON public.rate_limits TO authenticated;
GRANT UPDATE ON public.rate_limits TO authenticated;
GRANT DELETE ON public.rate_limits TO service_role;
GRANT INSERT ON public.rate_limits TO service_role;
GRANT SELECT ON public.rate_limits TO service_role;
GRANT UPDATE ON public.rate_limits TO service_role;
GRANT DELETE ON public.security_events TO anon;
GRANT INSERT ON public.security_events TO anon;
GRANT SELECT ON public.security_events TO anon;
GRANT UPDATE ON public.security_events TO anon;
GRANT DELETE ON public.security_events TO authenticated;
GRANT INSERT ON public.security_events TO authenticated;
GRANT SELECT ON public.security_events TO authenticated;
GRANT UPDATE ON public.security_events TO authenticated;
GRANT DELETE ON public.security_events TO service_role;
GRANT INSERT ON public.security_events TO service_role;
GRANT SELECT ON public.security_events TO service_role;
GRANT UPDATE ON public.security_events TO service_role;
GRANT DELETE ON public.tap_events TO anon;
GRANT INSERT ON public.tap_events TO anon;
GRANT SELECT ON public.tap_events TO anon;
GRANT UPDATE ON public.tap_events TO anon;
GRANT DELETE ON public.tap_events TO authenticated;
GRANT INSERT ON public.tap_events TO authenticated;
GRANT SELECT ON public.tap_events TO authenticated;
GRANT UPDATE ON public.tap_events TO authenticated;
GRANT DELETE ON public.tap_events TO service_role;
GRANT INSERT ON public.tap_events TO service_role;
GRANT SELECT ON public.tap_events TO service_role;
GRANT UPDATE ON public.tap_events TO service_role;
GRANT DELETE ON public.taps TO anon;
GRANT INSERT ON public.taps TO anon;
GRANT SELECT ON public.taps TO anon;
GRANT UPDATE ON public.taps TO anon;
GRANT DELETE ON public.taps TO authenticated;
GRANT INSERT ON public.taps TO authenticated;
GRANT SELECT ON public.taps TO authenticated;
GRANT UPDATE ON public.taps TO authenticated;
GRANT DELETE ON public.taps TO service_role;
GRANT INSERT ON public.taps TO service_role;
GRANT SELECT ON public.taps TO service_role;
GRANT UPDATE ON public.taps TO service_role;
GRANT DELETE ON public.user_roles TO anon;
GRANT INSERT ON public.user_roles TO anon;
GRANT SELECT ON public.user_roles TO anon;
GRANT UPDATE ON public.user_roles TO anon;
GRANT DELETE ON public.user_roles TO authenticated;
GRANT INSERT ON public.user_roles TO authenticated;
GRANT SELECT ON public.user_roles TO authenticated;
GRANT UPDATE ON public.user_roles TO authenticated;
GRANT DELETE ON public.user_roles TO service_role;
GRANT INSERT ON public.user_roles TO service_role;
GRANT SELECT ON public.user_roles TO service_role;
GRANT UPDATE ON public.user_roles TO service_role;

-- Function execute grants
REVOKE EXECUTE ON FUNCTION public.admin_ban_user(_user_id uuid, _ban boolean, _reason text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_set_user_role(_user_id uuid, _role app_role, _grant boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_rate_limit(_bucket text, _max integer, _window_secs integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.claim_official_card(_uid text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_security_event(_severity text, _category text, _action text, _route text, _user_agent text, _ip text, _details jsonb) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.normalize_card_uid() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.profile_is_visible(_profile_id uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_ban_user(_user_id uuid, _ban boolean, _reason text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_ban_user(_user_id uuid, _ban boolean, _reason text) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_user_role(_user_id uuid, _role app_role, _grant boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_role(_user_id uuid, _role app_role, _grant boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(_bucket text, _max integer, _window_secs integer) TO anon;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(_bucket text, _max integer, _window_secs integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.claim_official_card(_uid text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.claim_official_card(_uid text) TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(_user_id uuid, _role app_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.log_security_event(_severity text, _category text, _action text, _route text, _user_agent text, _ip text, _details jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.normalize_card_uid() TO service_role;
GRANT EXECUTE ON FUNCTION public.profile_is_visible(_profile_id uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO service_role;
